### ISSUE TITLE
Master's paper is not available

### ISSUE THREAD

**Issue by FulgurIgor** [Armaxis/jmg#14]
Dear Artem,

I wanted to share your master's degree paper, but, unfortunately, armaxis.ru is not reachable now, so, it is not possible to share it.

Could you please create a new place for your master's paper? Probably, in the repo, if it is possible.

Thank you in advance!

Best regards,
Igor

**Comment by Armaxis** [comment]
Hey Igor!

This issue just made my day and brought up the memories! Can't believe that after 9 years folks are still interested in my work :)

I didn't really use my website, so I stopped paying for the domain.. and forgot that my master's paper was there. Oops!

I'll upload the file in a bit. Stay tuned!

**Comment by Armaxis** [comment]
Done!
